export const wilayas = [
  { value: 'Adrar', label: '(1) Adrar - أدرار' },
  { value: 'Chlef', label: '(2) Chlef - الشلف' },
  { value: 'Laghouat', label: '(3) Laghouat - الأغواط' },
  { value: 'Oum El Bouaghi', label: '(4) Oum El Bouaghi - أم البواقي' },
  { value: 'Batna', label: '(5) Batna - باتنة' },
  { value: 'Béjaïa', label: '(6) Bejaia - بجاية' },
  { value: 'Biskra', label: '(7) Biskra - بسكرة' },
  { value: 'Béchar', label: '(8) Bechar - بشار' },
  { value: 'Blida', label: '(9) Blida - البليدة' },
  { value: 'Bouira', label: '(10) Bouira - البويرة' },
  { value: 'Tamanrasset', label: '(11) Tamanrasset - تامنغست' },
  { value: 'Tébessa', label: '(12) Tebessa - تبسة' },
  { value: 'Tlemcen', label: '(13) Tlemcen - تلمسان' },
  { value: 'Tiaret', label: '(14) Tiaret - تيارت' },
  { value: 'Tizi Ouzou', label: '(15) Tizi ouzou - تيزي وزو' },
  { value: 'Alger', label: '(16) Alger - الجزائر' },
  { value: 'Djelfa', label: '(17) Djelfa - الجلفة' },
  { value: 'Jijel', label: '(18) Jijel - جيجل' },
  { value: 'Sétif', label: '(19) Setif - سطيف' },
  { value: 'Saïda', label: '(20) Saida - سعيدة' },
  { value: 'Skikda', label: '(21) Skikda - سكيكدة' },
  { value: 'Sidi Bel Abbès', label: '(22) Sidi Bel Abbes - سيدي بلعباس' },
  { value: 'Annaba', label: '(23) Annaba - عنابة' },
  { value: 'Guelma', label: '(24) Guelma - قالمة' },
  { value: 'Constantine', label: '(25) Constantine - قسنطينة' },
  { value: 'Médéa', label: '(26) Medea - المدية' },
  { value: 'Mostaganem', label: '(27) Mostaganem - مستغانم' },
  { value: "M'Sila", label: "(28) M'sila - المسيلة" },
  { value: 'Mascara', label: '(29) Mascara - معسكر' },
  { value: 'Ouargla', label: '(30) Ouargla - ورقلة' },
  { value: 'Oran', label: '(31) Oran - وهران' },
  { value: 'El Bayadh', label: '(32) El Bayadh - البيض' },
  { value: 'Illizi (wilaya restreinte)', label: '(33) Illizi - إيليزي' },
  {
    value: 'Bordj Bou Arreridj',
    label: '(34) Bordj Bou Arreridj - برج بوعريرج',
  },
  { value: 'Boumerdès', label: '(35) Boumerdes - بومرداس' },
  { value: 'El Tarf', label: '(36) El Tarf - الطارف' },
  { value: 'Tindouf (wilaya restreinte)', label: '(37) Tindouf - تندوف' },
  { value: 'Tissemsilt', label: '(38) Tissemsilt - تيسمسيلت' },
  { value: 'El Oued', label: '(39) El Oued - الوادي' },
  { value: 'Khenchela', label: '(40) Khenchela - خنشلة' },
  { value: 'Souk Ahras', label: '(41) Souk Ahras - سوق أهراس' },
  { value: 'Tipaza', label: '(42) Tipaza - تيبازة' },
  { value: 'Mila', label: '(43) Mila - ميلة' },
  { value: 'Aïn Defla', label: '(44) Ain Defla - عين الدفلة' },
  { value: 'Naâma', label: '(45) Naama - النعامة' },
  { value: 'Aïn Témouchent', label: '(46) Ain Temouchent - عين تيموشنت' },
  { value: 'Ghardaïa', label: '(47) Ghardaia - غرداية' },
  { value: 'Relizane', label: '(48) Relizane - غليزان' },
];
